2023-01-21 12:21:26.021 | ERROR    | __main__:_make_request:32 - Erro de conexão ao fazer %s request para %s: %s
2023-01-21 12:22:43.123 | ERROR    | __main__:_make_request:32 - Erro de conexão ao fazer GET request para /user: No connection adapters were found for '127.0.0.1:8000/api/v1//user'
2023-01-21 12:22:49.932 | ERROR    | __main__:_make_request:32 - Erro de conexão ao fazer GET request para user: No connection adapters were found for '127.0.0.1:8000/api/v1/user'
2023-01-21 12:23:35.746 | ERROR    | __main__:_make_request:41 - Erro ao fazer GET pedido para /usuario: {'detail': 'As credenciais de autenticação não foram fornecidas.'} (Erro de codigo 403)
2023-01-23 12:51:05.566 | ERROR    | test.tests_project:_make_request:26 - Erro de conexão ao fazer GET request para /product: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /api/v1/product (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EC56357280>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2023-01-23 12:51:07.774 | ERROR    | test.tests_project:_make_request:26 - Erro de conexão ao fazer GET request para /product/lenovo: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /api/v1/product/lenovo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EC56D2D660>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2023-01-23 12:55:16.136 | ERROR    | test.tests_project:_make_request:26 - Erro de conexão ao fazer GET request para /product: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /api/v1/product (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FE5D7C7460>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2023-01-23 12:55:18.297 | ERROR    | test.tests_project:_make_request:26 - Erro de conexão ao fazer GET request para /product/lenovo: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /api/v1/product/lenovo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FE5E2415D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
